jobs:
  include:
    - stage: build docker images
      script:
      - docker build -t udagram-api-feed ./udagram-api-feed
      - docker build -t udagram-api-user ./udagram-api-user
      - docker build -t udagram-frontend ./udagram-frontend
      - docker build -t reverseproxy ./udagram-reverseproxy
    - stage: tag docker images
      script: 
      - docker tag udagram-api-feed jimezesinachi/udagram-api-feed:v1
      - docker tag udagram-api-user jimezesinachi/udagram-api-user:v1
      - docker tag udagram-frontend jimezesinachi/udagram-frontend:v1
      - docker tag reverseproxy jimezesinachi/reverseproxy:v1
    - stage: push docker images
      script: 
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - docker push sudkul/udagram-api-feed:v1