version: "3"
services:
  reverseproxy:
    pull:
      context: jimezesinachi/reverseproxy
    image: jimezesinachi/reverseproxy:v1
  backend_user:
    build:
      context: jimezesinachi/udagram-api-user
    image: jimezesinachi/udagram-api-user:v1
  backend_feed:
    build:
      context: jimezesinachi/udagram-api-feed
    image: jimezesinachi/udagram-api-feed:v1
  frontend:
    build:
      context: jimezesinachi/udagram-frontend
    image: jimezesinachi/udagram-frontend:v1